### ISSUE TITLE
Unclear Uhost installation guide: adding UTIM id to database

### ISSUE THREAD

**Issue by harryofskyrim** [connax-utim/documentation#4]
Documentation states:

> 3.  Add Utim ID in hex format to device_id column of udata table

After configuration and launch Uhost looks for UTIM id in upper case hex, so if the lower case hex id is added instead Utim and Uhost would never communicate:

mysql data:
`select * from udata;`
`+-----------+------+-------------+-------------+--------------------+----------------+---------------------+--------+`
`| device_id | name | session_key | config_hash | keep_alive_counter | status         | update_time         | sub_id |`
`+-----------+------+-------------+-------------+--------------------+----------------+---------------------+--------+`
`| 7574696d  | NULL | NULL        | NULL        |                  0 | STATUS_NEWBORN | 2018-11-15 12:23:15 |   NULL |`
`+-----------+------+-------------+-------------+--------------------+----------------+---------------------+--------+`
`1 row in set (0.01 sec)`

uhost_launcher.py log:
`process_inbound_item.py         Dummy-4   190                     run_worker: Invalid utim name: 7574696D`

Issue is resolved when changing `7574696d` to `7574696D` in udata table.

The importance of making id upper case is never stated, and in Utim example [config utimname](https://utim.readthedocs.io/en/latest/user/utim_installation.html) is listed in lower case, which is misleading.

**Comment by iMitro** [comment]
@harryofskyrim 
It's not describe in documentation because hex-string must be case-insensitive.
This is a bug of uhost-python that needs to be fixed.

I have described this problem [here](https://github.com/connax-utim/uhost-python/issues/1).

Since this is not about documentation, I close this issue.
